version: '3.9'

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
