### register user
POST http://localhost:8080/api/user/register
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "login": "Henry",
  "password": "qwerty"
}

### login user
POST http://localhost:8080/api/user/login
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "login": "Abrahm",
  "password": "sarah085"
}

### load order
POST http://localhost:8080/api/user/orders
Accept-Encoding: gzip, deflate, br
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ5MjgyNzEsImlhdCI6MTY2NDg4NTA3MSwidXNlcl9pZCI6N30.OFh9-WZ3yUsX8o-F8ZXg6R4FE9zVN_ehbaYnhD50wH0
Content-Type: text/plain

9278923470

### get orders
GET http://localhost:8080/api/user/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjUxOTQzODIsImlhdCI6MTY2NTE1MTE4MiwidXNlcl9pZCI6NH0.L6emPCWmv2GYyxMRZy36v7rsbRON52gZYRpyg45E7zA
