### register user
POST http://localhost:8080/api/user/register
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "login": "Henry",
  "password": "qwerty"
}

### login user
POST http://localhost:8080/api/user/login
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "login": "Abrahm",
  "password": "sarah085"
}

### load order
POST http://localhost:8080/api/user/orders
Accept-Encoding: gzip, deflate, br
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ4NjUxMjcsImlhdCI6MTY2NDgyMTkyNywidXNlcl9pZCI6NH0.SYDgvTEJg1L2zwobONtje-d29-LwNOxJy_jej0Em8P4
Content-Type: text/plain

12345678903
